var paper_titles = [
  "An Investigation into the Use of Recurrent Neural Networks for Predicting the Outcome of Goose Races",
  "Scaling Laws for Goose Shaped Transformers",
  "Network analysis of goose migration",
  "Predicting the optimal migration path for geese with Graph Neural Networks",
  "The Use of Transfer Learning for Automated Goose Classification",
  "Training a Goose Recognition Model with Pre-Trained Convolutional Neural Networks",
  "Learning to Recognize Geese by their Footprints",
  "Anomaly Detection in Goose Movement Data",
  "Reinforcement Learning from Goose Feedback",
  "Navigating With a Goose Brain: A Neurobiologically-Inspired Model for Robot Spatial Representation",
  "Risks from Learned Goosetimization",
  "Mastering the game of Goose with deep neural networks and tree search",
  "Scaling laws for Perceptrons",
  "Learning to learn without human feedback from human feedback",
  "Improving performance of logistic regression using reinforcement learning",
  "Ending world hunger with Recurrent Neural Networks",
  "Achieving Zero training time with Neural Networks",
  "Deep learning for nomadic goat herders",
  "Anomaly detection in time-series data with LSTM networks",
  "Transcending the CAP theorem with Bayesian inference",
  "Designing resilient architectures with fractal CNNs",
  "Random forest autoencoders for unsupervised learning",
  "Optimising deep networks with evolutionary algorithms",
  "A survey of all papers that Schmidhuber has ever written",
  "The unreasonable effectiveness of is all you need",
  "The aaaaapill: Theory and Practice",
  "When mesaoptimizers dream of electric sheep",
  "Bayesian optimization for automated theorem proving",
  "Crowdsourced annotated dataset of celebrity plastic surgery before and after images",
  "Anomaly detection in streaming data from the Large Hadron Collider",
  "Generative adversarial networks for fashion design",
  "Reinforcement learning to maximize likes on your Facebook page",
  "A comparative analysis of the shape rotation capabilities of self-attentive reinforcement learners vs. human baseline capabilities",
  "A hierarchical self-attentive neural extractive summarizer of proper grammatical structures",
  "Transformers is all you need",
  "Parameters is all you need",
  "Money is all you need",
  "\"All you need\" is all you need",
  "Nonsense AI paper titles is all you need",
  "The unreasonable effectiveness of transformers",
  "The unreasonable effectiveness of scaling",
  "Tne unreasonable effectiveness of parameters",
  "Making Deep Learning Go Brrrrrrrrrrr: A First Principles Approach",
  "A philosophical treatise on the theory of aligned catgirls",
  "Induction heads in transformers: An Electrical Engineering Approach",
  "Unreasonable Effectiveness: What it is and how to use it",
  "Learning to learn without gradient descent without gradient descent with gradient descent",
  "3e-4: is it really the best learning rate?",
  "Analysis of Transformer Safety: Too many layers?",
  "Generating malware with transformers",
  "Generating transformer improving software with transformers",
  "On the impossibility of humans",
]

var conference_names = [
  "International Conference on Learning Rates",
  "Neuroscientific International Primatological Society",
  "International Conference on Markup Languages",
  "Applied Applications Applicating Inapplicabilities",
]
